#
# Defines environment variables.
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# Configure python to use pyenv
# http://akbaribrahim.com/managing-multiple-python-versions-with-pyenv/
if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi

# Add yarn to path
export PATH=$PATH:/usr/local/Cellar/yarn/1.3.2/bin/yarn

# NVM config
export NVM_DIR=~/.nvm

# Add RVM to PATH for scripting
export PATH="$PATH:$HOME/.rvm/bin"

# This loads nvm bash_completion
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

# Create a shortcut for quick access to projecs directory
source /usr/local/bin/proj.sh

# Configure golang
export GOPATH="${HOME}/go"
export GOROOT="$(/usr/local/bin/brew --prefix golang)/libexec"
export PATH="$PATH:${GOPATH}/bin:${GOROOT}/bin"

# Configure AWS SAM
# Find your Python User Base path (where Python --user will install packages/scripts)
export PATH="$PATH:$HOME/Library/Python/2.7/bin"

# Configure history
# set history size
export HISTSIZE=15000

# save history after logout
export SAVEHIST=15000

# history file
export HISTFILE=~/.zhistory

# append into history file
setopt INC_APPEND_HISTORY

# save only one command if 2 common are same and consistent
setopt HIST_IGNORE_DUPS

# add timestamp for each entry
setopt EXTENDED_HISTORY
