# Configure history
# set history size
export HISTSIZE=15000

# save history after logout
export SAVEHIST=15000

# history file
export HISTFILE=~/.zhistory

# append into history file
setopt INC_APPEND_HISTORY

# save only one command if 2 common are same and consistent
setopt HIST_IGNORE_DUPS

# add timestamp for each entry
setopt EXTENDED_HISTORY

export PATH="${HOME}/.pyenv/shims:${PATH}"
