#
# Defines environment variables.
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# Configure python to use pyenv
# http://akbaribrahim.com/managing-multiple-python-versions-with-pyenv/
if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi

# Add golang to path
export PATH=$PATH:/usr/local/go/bin

# Add yarn to path
export PATH=$PATH:/usr/local/Cellar/yarn/1.3.2/bin/yarn

# NVM config
export NVM_DIR=~/.nvm

# Add RVM to PATH for scripting
export PATH="$PATH:$HOME/.rvm/bin"

# This loads nvm bash_completion
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
